In [11]:
#creating array
import numpy as np

arr=np.array([2,4,6,8])
print("Array is:",arr)

Array is: [2 4 6 8]


In [10]:
#creating 2d array
import numpy as np

arr=np.array([[2,4,6,8],[1,3,5,7]])
print("2D Array is:",arr)

2D Array is: [[2 4 6 8]
 [1 3 5 7]]


In [13]:
#arange function
import numpy as np

arr=np.arange(6)
print("Array range from 0 to 6:",arr)


Array range from 0 to 6: [0 1 2 3 4 5]


In [15]:
#arange function and shape function
import numpy as np

arr=np.arange(1,10,.5)
print("Array range:",arr)
print("5th element:",arr[4])
print(arr.shape)

Array range: [ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.
  8.5  9.   9.5]
5th element: 3.0
(18,)


In [27]:
#matrix multiplication
import numpy as np

arr=np.arange(4).reshape(2,2)
print("Matrix A:\n",arr)
arr2=np.arange(5,9).reshape(2,2)
print("Matrix B:\n",arr2)
m=np.dot(arr,arr2)
print("A x B:\n",m)

Matrix A:
 [[0 1]
 [2 3]]
Matrix B:
 [[5 6]
 [7 8]]
A x B:
 [[ 7  8]
 [31 36]]


In [18]:
#arange,reshape and transpose
import numpy as np

arr=np.arange(4).reshape(2,2)
print("2x2 array:\n",arr)
t=np.transpose(arr)
print("Transpose:",t)


2x2 array:
 [[0 1]
 [2 3]]
Transpose: [[0 2]
 [1 3]]


In [20]:
#Zeroes array
import numpy as np

arr=np.zeros([3,3])
print(arr)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [21]:
#Ones array
import numpy as np

arr=np.ones([2,2])
print(arr)

[[ 1.  1.]
 [ 1.  1.]]


In [23]:
#using random
import numpy as np

arr=np.random.random([3,3])
print(arr)

[[ 0.23284871  0.56763965  0.27343017]
 [ 0.07039789  0.30167603  0.87052144]
 [ 0.09905682  0.76414262  0.73144887]]


In [28]:
#lin space
import numpy as np
x=np.linspace(1,6,4)
print(x)

[ 1.          2.66666667  4.33333333  6.        ]


In [32]:
#svd
from scipy.linalg import svd
x=np.arange(9).reshape(3,3)
print(x)
p,q,r=svd(x)
print(p,"\n")
print(q,"\n")
print(r)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[-0.13511895  0.90281571  0.40824829]
 [-0.49633514  0.29493179 -0.81649658]
 [-0.85755134 -0.31295213  0.40824829]] 

[  1.42267074e+01   1.26522599e+00   5.89938022e-16] 

[[-0.4663281  -0.57099079 -0.67565348]
 [-0.78477477 -0.08545673  0.61386131]
 [-0.40824829  0.81649658 -0.40824829]]
