In [1]:
#matrix multiplication
import numpy as np

arr=np.arange(4).reshape(2,2)
print("Matrix A:\n",arr)
arr2=np.arange(5,9).reshape(2,2)
print("Matrix B:\n",arr2)
m=np.dot(arr,arr2)
print("A x B:\n",m)

Matrix A:
 [[0 1]
 [2 3]]
Matrix B:
 [[5 6]
 [7 8]]
A x B:
 [[ 7  8]
 [31 36]]
